name: Chore / Maintenance
description: Non-feature work (refactoring, CI, docs, deps)
labels: ["type:chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why is this needed now?
